"================vimrc==================
"Phil Fishbein

"set space as leader key
let mapleader = "\<Space>"

set nocompatible              " be iMproved, required
filetype off                  " required
filetype plugin indent on

" Vim-Plug
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'tpope/vim-rails'
" Initialize plugin system
call plug#end()

set background=dark
colorscheme solarized

" Make CtrlP use ag for listing the files. Way faster and no useless files.
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0

"Set up tab preferences
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

nmap 0 ^
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

" Ctrl+s to exit insert mode and write file
imap <C-s> <esc>:w<cr>

" Ctrl+p for fzf
nmap <C-p> :Files<cr>
nmap <leader>b :Buffers<cr>

set number                      " Display line numbers
set cursorline                  " Highlight current line
hi cursorline cterm=none        " Remove underline from current line
hi cursorlinenr ctermfg=red     " Make line number red
set history=1000                " Remember last 1000 commands

"In insert mode change cursor to line in iTerm 2 on macOS
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" Open new splits to the right and bottom, like most editors
set splitbelow
set splitright

" Kill bad habits
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

" split with current directory
nmap <leader>v :vnew <C-r>=escape(expand("%:p:h"), ' ') . '/'<cr>
nmap <leader>s :new <C-r>=escape(expand("%:p:h"), ' ') . '/'<cr>

" Move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk

" Copy the entire buffer into the system register
nmap <leader>co ggVG*y
